# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: gc
tagline: 'A poetry journal'
description: 'A personal poetry journal, diary and archive to share semifrequent poems throughout the year.'
url: https://www.georgecloake.com

# SEO
author:
  name: George Cloake
  url: https://www.georgecloake.com
  
twitter:
  username: GeorgeCloake
  card: summary
  
logo: /favicon.png

social:
  name: George Cloake
  links:
  - https://twitter.com/GeorgeCloake

# Paginate
paginate: 2
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Sidebar link settings
sidebar_home_link: true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

# Original theme
remote_theme: fongandrew/hydeout

# Analytics
google_analytics: UA-175425053-1
